name: AwesomePueblo
layout_spectrum: 0.07966579077765346
typography_spectrum: 0.3496295490767807
color:
  brandColors:
    - '#10222B'
    - '#95AB63'
    - '#BDD684'
    - '#E2F0D6'
    - '#F6FFE0'
  brandStrength: 0.9066335132811219
  lightness: 0.6615799940191209
  saturation: 0.4524022184778005
  rhythmicContrast: 0.8202029929962009
title: Salesforce Projects
navigation:
  - name: 'Step by Step Through Email-to-Case, again, again'
    id: cf21c575-c842-49e8-a52b-4f7d88f9a24b
    type: content
  - name: Partner Community Demo Setup
    id: a7074a64-11a7-4c50-810b-83e5e645baa1
    type: content
  - name: Marketing Flow to Delete Contacts and Create Lead records
    id: d02734d0-a11e-44b3-b3d3-05e9916bc924
    type: content
