layout_spectrum: 0.42634084168821573
typography_spectrum: 0.5477674349676818
color:
  brandStrength: 0.3838675457518548
  lightness: 0.24308055476285517
  saturation: 0.7029648332390934
  rhythmicContrast: 0.38434154633432627
  brandColors:
    - '#CFC291'
    - '#FFF6C5'
    - '#A1E8D9'
    - '#FF712C'
    - '#695D46'
name: AwesomePueblo
title: Salesforce Projects
