color:
  brandColors:
    - '#FFF8E3'
    - '#CCCC9F'
    - '#33332D'
    - '#9FB4CC'
    - '#DB4105'
  brandStrength: 1
  lightness: 0.731982
  rhythmicContrast: 0.658784
  saturation: 0.400901
layout_spectrum: 0
name: AwesomePueblo
title: Salesforce Projects
typography_spectrum: 1
